"use client"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Link from 'next/link'
import { useState } from 'react'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function DashbordLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const location = usePathname();
    const links = [
        {
            name: "Tableau de bord",
            url: "/dashbord",
            icon: <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" className='mr-1 ' viewBox="0 0 24 24"><path fill="currentColor" d="M19 21H5a1 1 0 0 1-1-1v-9H1l10.327-9.388a1 1 0 0 1 1.346 0L23 11h-3v9a1 1 0 0 1-1 1Zm-6-2h5V9.158l-6-5.455l-6 5.455V19h5v-6h2v6Z" /></svg> 
        },
        {
            name: "Produit",
            url: "/dashbord/produits",
            icon:<svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" className='mr-1 ' viewBox="0 0 24 24"><circle cx="5" cy="19" r="1" fill="currentColor" /><path fill="currentColor" d="M4 4h2v9H4z" /><path fill="currentColor" d="M7 2H3a1 1 0 0 0-1 1v18a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1Zm0 19H3V3h4Zm7-18v7h-3V3h3m1-1h-5v9h5V2Zm6 1v7h-3V3h3m1-1h-5v9h5V2Zm-8 12v7h-3v-7h3m1-1h-5v9h5v-9Zm6 1v7h-3v-7h3m1-1h-5v9h5v-9Z" /></svg>
        },
        {
            name: "Commande",
            url: "/dashbord/commandes",
            icon: <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" className='mr-1 ' viewBox="0 0 24 24"><path fill="currentColor" d="M4 13c-1.11 0-2 .89-2 2v4c0 1.11.89 2 2 2h4c1.11 0 2-.89 2-2v-4c0-1.11-.89-2-2-2m.2 1.5l1.06 1.05l-3.99 3.95l-2.53-2.55l1.07-1.05l1.47 1.49M4 3c-1.11 0-2 .89-2 2v4c0 1.11.89 2 2 2h4c1.11 0 2-.89 2-2V5c0-1.11-.89-2-2-2M4 5h4v4H4m8-4h10v2H12m0 12v-2h10v2m-10-8h10v2H12Z" /></svg>  
        },
        {
            name: "Livraison",
            url: "/dashbord/livraison",
            icon:  <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" className='mr-1 ' viewBox="0 0 32 32"><path fill="currentColor" d="M4 16h12v2H4zm-2-5h10v2H2z" /><path fill="currentColor" d="m29.919 16.606l-3-7A.999.999 0 0 0 26 9h-3V7a1 1 0 0 0-1-1H6v2h15v12.556A3.992 3.992 0 0 0 19.142 23h-6.284a4 4 0 1 0 0 2h6.284a3.98 3.98 0 0 0 7.716 0H29a1 1 0 0 0 1-1v-7a.997.997 0 0 0-.081-.394ZM9 26a2 2 0 1 1 2-2a2.002 2.002 0 0 1-2 2Zm14-15h2.34l2.144 5H23Zm0 15a2 2 0 1 1 2-2a2.002 2.002 0 0 1-2 2Zm5-3h-1.142A3.995 3.995 0 0 0 23 20v-2h5Z" /></svg> 
        }
    ]

    return (
        <html lang="en">
            <body className={inter.className}>
                <div className=''>
                    <div className='fixed w-[15%] h-screen overflow-auto shadow-lg bg-white'>
                        <div className='font-medium py-2 bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 text-md text-white text-center'>
                            Tableau de bord
                        </div>
                        <div className='mt-8'>
                            {
                                links.map((link, index) => (
                                    <Link href={link.url} className={`${location === link.url? 'bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 text-md text-white' : 'text-gray-700'} hover:bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 text-md hover:text-white flex font-medium items-center px-2 my-2  py-2`} key={index}>
                                       {link.icon} {link.name}
                                    </Link>
                                ))
                            }

                            <Link href={"/dashbord/users"} className='flex font-medium text-gray-800 items-center px-2 my-2 py-1.5 hover:text-white hover:bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 border-t border-gray-400 mt-6'>
                                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" className='mr-1' viewBox="0 0 256 256"><path fill="currentColor" d="M244.8 150.4a8 8 0 0 1-11.2-1.6A51.6 51.6 0 0 0 192 128a8 8 0 0 1-7.37-4.89a8 8 0 0 1 0-6.22A8 8 0 0 1 192 112a24 24 0 1 0-23.24-30a8 8 0 1 1-15.5-4A40 40 0 1 1 219 117.51a67.94 67.94 0 0 1 27.43 21.68a8 8 0 0 1-1.63 11.21ZM190.92 212a8 8 0 1 1-13.84 8a57 57 0 0 0-98.16 0a8 8 0 1 1-13.84-8a72.06 72.06 0 0 1 33.74-29.92a48 48 0 1 1 58.36 0A72.06 72.06 0 0 1 190.92 212ZM128 176a32 32 0 1 0-32-32a32 32 0 0 0 32 32Zm-56-56a8 8 0 0 0-8-8a24 24 0 1 1 23.24-30a8 8 0 1 0 15.5-4A40 40 0 1 0 37 117.51a67.94 67.94 0 0 0-27.4 21.68a8 8 0 1 0 12.8 9.61A51.6 51.6 0 0 1 64 128a8 8 0 0 0 8-8Z" /></svg> Users
                            </Link>
                            <Link href={"/dashbord/produits"} className='flex font-medium text-gray-800 items-center px-2 my-2 py-1.5 hover:text-white hover:bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500'>
                                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" className='mr-1' viewBox="0 0 256 256"><path fill="currentColor" d="M128 80a48 48 0 1 0 48 48a48.05 48.05 0 0 0-48-48Zm0 80a32 32 0 1 1 32-32a32 32 0 0 1-32 32Zm109.94-52.79a8 8 0 0 0-3.89-5.4l-29.83-17l-.12-33.62a8 8 0 0 0-2.83-6.08a111.91 111.91 0 0 0-36.72-20.67a8 8 0 0 0-6.46.59L128 41.85L97.88 25a8 8 0 0 0-6.47-.6a112.1 112.1 0 0 0-36.68 20.75a8 8 0 0 0-2.83 6.07l-.15 33.65l-29.83 17a8 8 0 0 0-3.89 5.4a106.47 106.47 0 0 0 0 41.56a8 8 0 0 0 3.89 5.4l29.83 17l.12 33.62a8 8 0 0 0 2.83 6.08a111.91 111.91 0 0 0 36.72 20.67a8 8 0 0 0 6.46-.59L128 214.15L158.12 231a7.91 7.91 0 0 0 3.9 1a8.09 8.09 0 0 0 2.57-.42a112.1 112.1 0 0 0 36.68-20.73a8 8 0 0 0 2.83-6.07l.15-33.65l29.83-17a8 8 0 0 0 3.89-5.4a106.47 106.47 0 0 0-.03-41.52Zm-15 34.91l-28.57 16.25a8 8 0 0 0-3 3c-.58 1-1.19 2.06-1.81 3.06a7.94 7.94 0 0 0-1.22 4.21l-.15 32.25a95.89 95.89 0 0 1-25.37 14.3L134 199.13a8 8 0 0 0-3.91-1h-3.83a8.08 8.08 0 0 0-4.1 1l-28.84 16.1A96 96 0 0 1 67.88 201l-.11-32.2a8 8 0 0 0-1.22-4.22c-.62-1-1.23-2-1.8-3.06a8.09 8.09 0 0 0-3-3.06l-28.6-16.29a90.49 90.49 0 0 1 0-28.26l28.52-16.28a8 8 0 0 0 3-3c.58-1 1.19-2.06 1.81-3.06a7.94 7.94 0 0 0 1.22-4.21l.15-32.25a95.89 95.89 0 0 1 25.37-14.3L122 56.87a8 8 0 0 0 4.1 1h3.64a8.08 8.08 0 0 0 4.1-1l28.84-16.1A96 96 0 0 1 188.12 55l.11 32.2a8 8 0 0 0 1.22 4.22c.62 1 1.23 2 1.8 3.06a8.09 8.09 0 0 0 3 3.06l28.6 16.29a90.49 90.49 0 0 1 .05 28.29Z" /></svg>  Parametres
                            </Link>
                        </div>
                    </div>
                    <div className='pl-[16%] p-2 bg-gray-50 w-full'>
                        <div className='flex justify-between px-5'>
                            <input type="search" name="" id="" className='border border-gray-300 rounded-full py-1 w-64 px-2 tetx-gray-600' placeholder='Recherche...' />
                            <div className='flex items-center space-x-2'>
                                <img src="/default.jpg" alt="" className='h-8 w-8 rounded-full' />
                                <div>
                                    Geedoo Kanda
                                </div>
                            </div>
                        </div>
                        {children}
                    </div>
                </div>
            </body>
        </html>
    )
}
